AWSTemplateFormatVersion: '2010-09-09'
Description: Simple KDA Flink application
Parameters:
  ArtemisAnalyticsJarFile:
    Type: String
    Default: artemis-analytics.jar

  VersionSuffix:
    Type: String
    Default: -v1

  KafkaTruststoreKey:
    Type: String
    Default: mix.4096.client.truststore.jks
  
  IDNPaths:
    Description: these are the WAF paths the we do phonenumber check when processing waf request thru artemis
    Type: String
    Default: /credential_lookup/v1,/challenge/password/v1,/verification_code/send/v1,/password_reset/v1

  BlockMethods:
    Description: data sources to be analyzed(cdn,waf,launch...)
    Type: String
    Default: cdn,launch,isbot
  
Mappings:
  Accounts:
    "439314357471": # litx test
      s3BucketName: "litx-test-artemis-analytics"
      commerceAccount: "734176943427"
    "439413396736": # litx prod
      s3BucketName: "litx-prod-artemis-analytics"
      commerceAccount: "734147128161"

  Networks:
    "439314357471":
      "VPC": "vpc-0c79181af7cd89765"
      "Subnet": "subnet-0af00467fb8f8713f"
      "SG": "sg-024f6ba21996520d6"
    "439413396736":
      "VPC": "vpc-099901a9739cc760a"
      "Subnet": "subnet-035cc1fa75d8d0584"
      "SG": "sg-0610c67f236db9c22"
  Kafka:
#    TODO fetch the secret from the SSM
    "439314357471": # litx test
      BootstrapServers: "alikafka-post-cn-lbj3d0eqm002-1.alikafka.aliyuncs.com:9093,alikafka-post-cn-lbj3d0eqm002-2.alikafka.aliyuncs.com:9093,alikafka-post-cn-lbj3d0eqm002-3.alikafka.aliyuncs.com:9093"
      username: "ArtemisCDNKafka"
      password: "5ZMvI2YPuVrahN5c3aTrhZt3QGkoKegV"
    "439413396736": # litx prod
      BootstrapServers: "alikafka-post-cn-x0r3g5hjf005-1.alikafka.aliyuncs.com:9093,alikafka-post-cn-x0r3g5hjf005-2.alikafka.aliyuncs.com:9093,alikafka-post-cn-x0r3g5hjf005-3.alikafka.aliyuncs.com:9093"
      username: "aliCdnLogKafka"
      password: "aliCdnLogKafka123"

Resources:

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/kinesis-analytics/artemis-analytics${VersionSuffix}'

  LogStream:
    Type: AWS::Logs::LogStream
    DependsOn: LogGroup
    Properties:
      LogGroupName: !Sub '/aws/kinesis-analytics/artemis-analytics${VersionSuffix}'
      LogStreamName: !Sub 'artemis-analytics${VersionSuffix}'

  ArtemisAnalytics:
    Type: AWS::KinesisAnalyticsV2::Application
    Properties:
      ApplicationName: !Sub 'artemis-analytics${VersionSuffix}'
      RuntimeEnvironment: FLINK-1_13
      ServiceExecutionRole: !Sub 'arn:aws-cn:iam::${AWS::AccountId}:role/teams/anti-bot/artemis-analytics-kinesis-execution-role${VersionSuffix}'
      ApplicationConfiguration:
        ApplicationCodeConfiguration:
          CodeContent:
            S3ContentLocation:
              BucketARN: !Join [ ':', ['arn:aws-cn:s3::', !FindInMap [Accounts, !Ref "AWS::AccountId", s3BucketName]] ]
              FileKey: !Ref ArtemisAnalyticsJarFile
          CodeContentType: 'ZIPFILE'
        EnvironmentProperties:
          PropertyGroups:
            - PropertyGroupId: 'cdnLogKafka'
              PropertyMap:
                AliKafkaBootstrapServers: !FindInMap [Kafka, !Ref "AWS::AccountId", BootstrapServers]
                KafkaConsumerGroupId: 'ali_cdn_log_group'
                KafkaSourceTopic: 'ali_cdn_filtered_log'
                TruststoreS3Bucket: !FindInMap [Accounts, !Ref "AWS::AccountId", s3BucketName]
                TruststoreS3Path: !Sub 'truststore/${KafkaTruststoreKey}'
                username: !FindInMap [Kafka, !Ref "AWS::AccountId", username]
                password: !FindInMap [Kafka, !Ref "AWS::AccountId", password]
#            - PropertyGroupId: 'wafLogKafka'
#              PropertyMap:
#                AliKafkaBootstrapServers: !Ref AliWAFKafkaBootstrapServers
#                KafkaConsumerGroupId: 'ali_waf_log_group'
#                KafkaSourceTopic: 'ali_waf_log'
#                TruststoreS3Bucket: !FindInMap [Accounts, !Ref "AWS::AccountId", s3BucketName]
#                TruststoreS3Path: !Sub 'truststore/${KafkaTruststoreKey}'
#                username: 'aliWafLogKafka'
#                password: 'aliWafLogKafka123'
            - PropertyGroupId: rulesBucket
              PropertyMap:
                RulesBucketName: !FindInMap [Accounts, !Ref "AWS::AccountId", s3BucketName]
                RulesKeyName: 'rules/rule'
            - PropertyGroupId: 'checkPath'
              PropertyMap:
                urlPath: !Ref IDNPaths
            - PropertyGroupId: 'sink'
              PropertyMap:
                methods: !Ref BlockMethods
            - PropertyGroupId: 'isbotResult'
              PropertyMap:
                commerceRoleArn: !Join
                    - ''
                    - - 'arn:aws-cn:iam::'
                      - !FindInMap [ Accounts, !Ref "AWS::AccountId", commerceAccount ]
                      - ':role/role_to_access_kds_cross_account_artemis'
        ApplicationSnapshotConfiguration:
          SnapshotsEnabled: False
        FlinkApplicationConfiguration:
          CheckpointConfiguration:
            CheckpointingEnabled: False
            ConfigurationType: CUSTOM
          MonitoringConfiguration:
            ConfigurationType: CUSTOM
            LogLevel: INFO
            MetricsLevel: APPLICATION
        VpcConfigurations:
          - SecurityGroupIds:
            - !FindInMap [Networks, !Ref "AWS::AccountId", SG]
            SubnetIds:
            - !FindInMap [Networks, !Ref "AWS::AccountId", Subnet]

  BasicApplicationV2CloudWatchLoggingOption:
    Type: AWS::KinesisAnalyticsV2::ApplicationCloudWatchLoggingOption
    Properties:
      ApplicationName:
        Ref: ArtemisAnalytics
      CloudWatchLoggingOption:
        LogStreamARN:
          Fn::Join:
          - ":"
          - - arn:aws-cn:logs
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - log-group
            - Ref: LogGroup
            - log-stream
            - Ref: LogStream
  CpuUtilizationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: CPU alarm for apache flink[artemis-analytics]
      AlarmActions:
        - !Sub "arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:gc-artemis-alerts"
      MetricName: cpuUtilization
      Namespace: AWS/KinesisAnalytics
      Statistic: Average
      Period: '60'
      EvaluationPeriods: '3'
      Threshold: '90'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Application
          Value:
            Ref: ArtemisAnalytics
  MemoryUtilizationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Memory alarm for apache flink[artemis-analytics]
      AlarmActions:
        - !Sub "arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:gc-artemis-alerts"
      MetricName: heapMemoryUtilization
      Namespace: AWS/KinesisAnalytics
      Statistic: Average
      Period: '300'
      EvaluationPeriods: '3'
      Threshold: '80'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Application
          Value:
            Ref: ArtemisAnalytics